### PR TITLE
refactor bug report mod version to accept versions until 1.3.7 

### PR DESCRIPTION
**Pull request by mayfairr**

### CODE REVIEW

**Comment by HOIYA1010** [comment]
i downloaded the version 1.4.0 and when i open my world i get the error " failed steam timed out" i don't know how to fix it or what to do or how to fix it.

**Comment by tomlloydDEV** [comment]
my Co-Op partners health bar went very small so he was easily killed and his attacks were not registering on enemies. he reinstalled the mod and this fixed the issue.

**Comment by Auraora** [comment]
Having a bug with torrent where once he dies from fall damage(and you die with him) he cannot be resummoned and does not ask for a flask to be revived. I play this mod on the latest release as on this day (12/20/22)

**Comment by garbageday666** [comment]
Hello. We were using the modded version of the game normally and were beginning the Blaidd questline. I snapped to get him to come down from the top of the mistwood ruins. He then jumped off as normal, but took fall damage and immediately permanently died. 12/21/22

**Comment by joeygayhunt** [comment]
someone invaded

**Comment by koozaa** [comment]
Had an issue with locking on playing as the host, this is specifically against enemies mounted on horseback and seems to happen most frequently when I myself am on horseback fighting them. Lock on will rapidly break, change enemies, refuse to switch targets, or just outright not work at all. This only starts after a player connects to my session.

I am on the newest version and I do not believe this bug has been reported here, although I've seen a few complaints about it on reddit.

**Comment by Garde3** [comment]
Having an issue with being suck of endless load screens when trying to go into the roundtable. Reinstalled the mod, picking another character, and simply waiting seems to lead to nothing changing.

**Comment by W0lf2905** [comment]
> Having an issue with being suck of endless load screens when trying to go into the roundtable. Reinstalled the mod, picking another character, and simply waiting seems to lead to nothing changing.

i have the same Problem i have this bug on two safe files.

**Comment by Kaplan1232** [comment]
I was in a coop play with a friend we wantet to travel to the Roundtabel (The Safe spot with all the NPC) but we are stuck in a loading screen. it reaches 100% in 1 sec and reload again and again can some help us out

**Comment by TheEmojiMan** [comment]
Recently me and a friend have been playing together using this mod, everything was running perfectly, up until we started fighting a boss in Caelid and suddenly we noticed our stats had drastically decreased. We had stats of 30 Vigor and after teleporting to church of Elle, we had our health, FP and stamina halved, even our weapons were doing minimal damage. and as we teleported to more places via grace, our stats kept decreasing further.

Now, if we disable wanderer joining so its a solo world, our stats return to normal, but the moment one of us use the tiny great pot to allow the other to join, our stats instantly drop.

**Comment by DukeNewcmb** [comment]
Friend and I having issues in Limgrave Tunnels with lifts. Not appearing/not working

**Comment by HotokeIgarashi** [comment]
When i download the mod i have the launch_elden_ring_seamlesscoop not as exe and i dont know why a friend off mine donwloaded the mod to and he got the exe data

**Comment by HotokeIgarashi** [comment]
> When i download the mod i have the launch_elden_ring_seamlesscoop not as exe and i dont know why a friend off mine donwloaded the mod to and he got the exe data

**Comment by thewildwookiee** [comment]
Alexander bugged when we helped him And when fighting my friends and I notice that we lose targeting on the some enemy's or bosses and it doesn't want to retarget

**Comment by PixelTrasher** [comment]
I was hosting some friends in my world and we retrieved the Smithing-Stone Miner's Bell Bearing [1]. We teleported back to the roundtable hold to give the Twin Maiden Husks our bell bearings. My friend went ahead before me and gave the Twin Maiden Husks his bell, and now I am unable to give the maidens my bell. I also do not have the shop available to me when I talk to the maidens. When I click "Offer a bell bearing", the message "No bell bearing to offer" appears. I've checked my inventory, and I do indeed have the bell bearing. I have verified file integrity through steam to try to fix this to no avail. I have not tried going to his world and delivering the bell to her yet, but it would be mighty unfortunate if I was unable to access the shop unless I go to him. I think I'll try anyways, because there could be a possibility that if I give her mine it might unlock for me in general. We'll see. But for now, be careful to give your bell bearings when you are alone!

**Comment by SkidadleSkidoodle** [comment]
So this mod is super cool, upon playing we found a few bugs. Probably the biggest is the horse, when a player gets on a horse they vanish into ether XD. Another simple problem was when one person places a marker and another player removed it he disconnected.

Super awesome mod hope it keeps progressing

**Comment by Infer123123** [comment]
When you go to grace and tell melina your off to the roundtable hold its bugs and you cant move or go to options and you have to leave the game

**Comment by laf2099** [comment]
I am having an issue with the UI prompts always being the PC button prompts when using a controller instead of the default xbox button prompts. I attempted to fix this by using the PS4/PS5 UI mod via ModEngine 2, but using this mod only changes the controller in the settings menu in game and has no affect on the button prompts when actually playing the game. Not sure if there is an easy fix that I can do on my side, but for now, it is just a mild frustration I have to put up with. Also wanted to say thanks for creating this mod!

**Comment by BazookaJoe1984** [comment]
First off, great mod.  When it's working well, we're having a blast.  We have a team of 4 of us, 3 of us don't have a lot of issues, however, the 4th person is constantly getting returned back to his world only after a short amount of time.  We have tried each person being the "host" and it still returns him back after a brief time in that specific world.  We have tried to match each other's IPV4 address's with 8.8.8.8 as the primary and 8.8.4.4 as the alternative, but it didn't seem to help him.  We believe it's something happening on his end, but we just don't know what it is.  His internet is fast enough, 300 Mbps down and 300 up. He is on Wifi but it is relatively stable.  Any input would be appreciated!

**Comment by ritaayio** [comment]
Thanks for the great mod! But me and my friend occurred some problems (In 1.4.2) and hopefully these things can be fixed. Thanks again!
The first thing is Stakes of Marika. It does not work at all. The option for you to choose the location to revive will not show up and you'll just revive at site of grace.
The second thing I'm not sure if it's a bug or not, but we have a lot of connecting issue when we're in the catacombs. The game will keep freezing and closing by itself.
The third thing is Roundtable Hold. When Melina trys to bring both of the players there, she'll just stare at you and do nothing. The option will not appear and you can't do anything but alt tap the game. Another thing is about Ensha. After Ensha invading you, Roundtable Hold will be no npcs there and you won't get the reward. You'll need to go back to your own world to fix these things

**Comment by thewildwookiee** [comment]
> Thanks for the great mod! But me and my friend occurred some problems (In 1.4.2) and hopefully these things can be fixed. Thanks again! The first thing is Stakes of Marika. It does not work at all. The option for you to choose the location to revive will not show up and you'll just revive at site of grace. The second thing I'm not sure if it's a bug or not, but we have a lot of connecting issue when we're in the catacombs. The game will keep freezing and closing by itself. The third thing is Roundtable Hold. When Melina trys to bring both of the players there, she'll just stare at you and do nothing. The option will not appear and you can't do anything but alt tap the game. Another thing is about Ensha. After Ensha invading you, Roundtable Hold will be no npcs there and you won't get the reward. You'll need to go back to your own world to fix these things

The stake of Marika is disabled in online play, as it causes connection problems.

Please do read before downloading.

**Comment by deaneko7** [comment]
Since the update to 1.4.2，I has got stuck in the loading interface when I join my friend's world and transmit blessing point.And it happens very often，is this a network problem？Or this is a bug？

**Comment by George30p** [comment]
Just installed as of version 1.4.2, me and a friend went over to Caelid to kill the sleeping dragon but when we were ready to fight it, it had perma despawned without us getting runes. To help this is what happened:
- Got the grace at the fort behind the sleeping dragon.
- Went inside the fort to get the radagons soreseal.
- Ran outside and my friend rested at the grace but a bat wasnt despawned and killed them. (I didnt rest at the grace because I landed on the wrong side of the wall so had to go around).
- They then respawned at the grace, we killed the bat and then we realised the dragon wasnt there anymore.


Loving the mod though btw but just wanted to report the bug if it helps :)

**Comment by antnbr** [comment]
> When you go to grace and tell melina your off to the roundtable hold its bugs and you cant move or go to options and you have to leave the game

Same problem here. It happened on the Margit arena boss fight site of grace but we tested it and it seems to be an issue with any site of grace. Only thing you ccan do is alt-f4 the game as characters stare blankly around the site of grace without anything happenning. We had to split together to our own worlds and asked Melina again to teleport us and then we rejoined at the roundtable hold without problems

**Comment by Xilolithe** [comment]
Me and my friend finished the Elden Beast fight and went to the stone platform, he died during the fight but I respawned him, he could not activate Ranni's summon sign and when I did he didn't get taken to the cutscene. It has counted as him completing the game because he can start new game+ but he didn't get the achievement.

**Comment by Xilolithe** [comment]
For some reason NPC's will just randomly not appear for me or my friend, or even sometimes it allows only one of us to see the NPC. Leaving usually results in the NPC being there. Eventually they will show back up but I just want it to be known, sorry if this problem has already been stated. This mostly aaffects the Roundtable where Roderika will just be stood at the fire place not offering her services and Enia completely disappearing or floating

**Comment by Xilolithe** [comment]
> For some reason NPC's will just randomly not appear for me or my partners, or even sometimes it allows only one of us to see the NPC. Leaving usually results in the NPC being there but so far twice they have just not appeared, even after I separated the session. Eventually they will show back up but I just want it to be known, sorry if this problem has already been stated.

When you separate from the session sit at a site of grace that will usually make the NPC's go where they should be.

**Comment by Goonmaster** [comment]
Not me, but one of my friends couldn't do the event with Melina at the Forge. Her dialogue option wouldn't pop up so he went to his own world and it still wasn't there so he can't watch the cutscene. (He hasn't finished the main story before.) I tried having him make sure he did the required Melina encounters, like the one after the Morgott fight in case they didn't count for him for whatever reason but no dice. Thanks for any help

**Comment by vivistreamt** [comment]
We noticed several bugs during boss fights
also with wolfs in the one cave

leaving you my twitch vods and clips here:
timestamps: 02:25:00 boss red wolf from Radagon
also you can see that I see my partner not walking. Instead he slides over the ground sometimes (f.e. right after first timestamp)
also Rennala bug: 03:23:00
https://www.twitch.tv/videos/1703418996

we obviously couldnt repeat the boss fight which was very unsatisfying to win so easy

one more question: is its supposed to remove some of the life points after dying and resetting it at the grace points?

**Comment by vythikas** [comment]
hi! playing on 1.4.2. my friend and I had a glitch where after making it to margit (and dying) and resting at site of grace to talk to melina to take us to roundtable hold, host got the dialogue to go to roundtable hold, but guest did not. host was stuck only able to turn camera - couldn't cancel the dialogue with melina etc. guest stood from grace and tried again to talk to melina. they got the go to roundtable hold option, but then both were stuck without any options. had to force quit.

**Comment by overfus** [comment]
Soft lock on a grace because of a dialogue with Melina regarding the Round Table 

Conditions: 
-Sitting together in front of a grace 
-Initiate dialogue with Melina to be taken to the round table for the first time

**Comment by rkgs** [comment]
> Just installed as of version 1.4.2, me and a friend went over to Caelid to kill the sleeping dragon but when we were ready to fight it, it had perma despawned without us getting runes. To help this is what happened:
> 
> * Got the grace at the fort behind the sleeping dragon.
> * Went inside the fort to get the radagons soreseal.
> * Ran outside and my friend rested at the grace but a bat wasnt despawned and killed them. (I didnt rest at the grace because I landed on the wrong side of the wall so had to go around).
> * They then respawned at the grace, we killed the bat and then we realised the dragon wasnt there anymore.
> 
> Loving the mod though btw but just wanted to report the bug if it helps :)
> 
> Update: The runes and dragon hearts came through as rewards later on whilst we were playing as if we had killed the dragon.

I had something similar happen, a friend and I went up the Spiritspring at the nearby Minor Erdtree to reach Fort Faroth to get Radagon's Soreseal, and it was either when we approached the grace outside of Fort Faroth Greyoll or we sat down at the site of grace that the big dragon (Greyoll) died instantly, and along with the 5 other dragons that it kills when she dies.

On version 1.4.2 as well.

**Pull request closed without merging**
