### PR TITLE
Update README to reflect this being the wrong place to report bugs

### PR DESCRIPTION
**Pull request by Tyfyter**
Do not report bugs here, this is not a place to report bugs, read the title, report bugs at https://discord.com/invite/er-seamless-coop-979042878091329587

لا تبلغ عن الأخطاء هنا، هذا ليس المكان المناسب للإبلاغ عن الأخطاء، اقرأ العنوان، أبلغ عن الأخطاء على https://discord.com/invite/er-seamless-coop-979042878091329587

请勿在此处报告错误，这不是报告错误的地方，请阅读标题，在 https://discord.com/invite/er-seamless-coop-979042878091329587 报告错误

Rapporteer hier geen bugs, dit is niet de plaats om bugs te melden, lees de titel, rapporteer bugs op https://discord.com/invite/er-seamless-coop-979042878091329587

Huwag mag-ulat ng mga bug dito, hindi ito lugar para mag-ulat ng mga bug, basahin ang pamagat, mag-ulat ng mga bug sa https://discord.com/invite/er-seamless-coop-979042878091329587

Ne signalez pas de bugs ici, ce n'est pas un endroit pour signaler des bugs, lisez le titre, signalez les bugs sur https://discord.com/invite/er-seamless-coop-979042878091329587

Melden Sie hier keine Fehler. Dies ist nicht der richtige Ort zum Melden von Fehlern. Lesen Sie den Titel und melden Sie Fehler unter https://discord.com/invite/er-seamless-coop-979042878091329587.

Μην αναφέρετε σφάλματα εδώ, αυτό δεν είναι μέρος για να αναφέρετε σφάλματα, διαβάστε τον τίτλο, αναφέρετε σφάλματα στη διεύθυνση https://discord.com/invite/er-seamless-coop-979042878091329587

Mai hōʻike i nā pōpoki ma aneʻi, ʻaʻole kēia kahi e hōʻike ai i nā pōpoki, heluhelu i ke poʻo inoa, hōʻike i nā pōpoki ma https://discord.com/invite/er-seamless-coop-979042878091329587

אל תדווח על באגים כאן, זה לא המקום לדווח על באגים, קרא את הכותרת, דווח על באגים בכתובת https://discord.com/invite/er-seamless-coop-979042878091329587

यहां बग की रिपोर्ट न करें, यह बग की रिपोर्ट करने की जगह नहीं है, शीर्षक पढ़ें, बग की रिपोर्ट यहां करें https://discord.com/invite/er-seamless-coop-979042878091329587

Ne jelentsd a hibákat itt, ez nem hely a hibák bejelentésére, olvasd el a címet, jelentsd a hibákat a https://discord.com/invite/er-seamless-coop-979042878091329587 címen.

여기에서 버그를 보고하지 마세요. 이곳은 버그를 보고하고, 제목을 읽고, https://discord.com/invite/er-seamless-coop-979042878091329587 에서 버그를 보고하는 곳이 아닙니다.

Rapportéiert keng Bugs hei, dëst ass keng Plaz fir Bugs ze mellen, liest den Titel, mellt Bugs op https://discord.com/invite/er-seamless-coop-979042878091329587

Kaua e ripoata nga pepeha ki konei, ehara tenei i te waahi ki te tuku korero i nga pepeha, panuihia te taitara, ripoata nga pepeha i https://discord.com/invite/er-seamless-coop-979042878091329587

Ikke rapporter feil her, dette er ikke et sted å rapportere feil, les tittelen, rapporter feil på https://discord.com/invite/er-seamless-coop-979042878091329587

Não reporte bugs aqui, este não é um lugar para reportar bugs, leia o título, reporte bugs em https://discord.com/invite/er-seamless-coop-979042878091329587

Не сообщайте об ошибках здесь, это не место для сообщений об ошибках. Прочтите заголовок и сообщите об ошибках по адресу https://discord.com/invite/er-seamless-coop-979042878091329587.

अत्र दोषान् न प्रतिवेदयन्तु, एतत् दोषाणां सूचनां दातुं, शीर्षकं पठितुं, https://discord.com/invite/er-seamless-coop-979042878091329587 इत्यत्र दोषान् प्रतिवेदयितुं स्थानं नास्ति

Nun signalari li bug ccà, chistu nun è nu postu pi signalari li bug, lèggiri lu tìtulu, signalari li bug a https://discord.com/invite/er-seamless-coop-979042878091329587

Ha ku soo wargelin dhiqlaha halkan, halkan maaha meel laga soo sheego dhiqlaha, akhri ciwaanka, ka warbixinta cayayaanka https://discord.com/invite/er-seamless-coop-979042878091329587

Rapportera inte buggar här, det här är inte en plats att rapportera buggar, läs rubriken, rapportera buggar på https://discord.com/invite/er-seamless-coop-979042878091329587

Không báo lỗi ở đây, đây không phải là nơi báo lỗi, đọc tiêu đề, báo lỗi tại https://discord.com/invite/er-seamless-coop-979042878091329587

Peidiwch â riportio chwilod yma, nid yw hwn yn lle i riportio chwilod, darllenwch y teitl, riportiwch chwilod yn https://discord.com/invite/er-seamless-coop-979042878091329587

### CODE REVIEW

**Comment by andredsantos82** [comment]
Hello, 
I'm sorry about the level of English, I'm not fluent and I'm using the translator.
I downloaded version 1.5.1 and played it for about 2 hours with my friend, and we are having a very annoying problem with the mount. When the Torrent dies, flask is used to revive it, but for some reason it doesn't appear to revive and we can't summon it, this problem is only for Coop, the Host is normal. 
Even if it doesn't die, this error occurs.
To fix this problem, I had to return to my world.

**Comment by Tyfyter** [comment]
This is not a suitable place to report issues.
This is a pull request attempting to change the repository's description to reflect that there is no such place in it.
Please report your issue in the discord server linked in the commit instead of the PR comments.

**Comment by Soinug** [comment]
你好 The Convergence1.4.2.1 和 Seamless Co-op一起使用会让Seamless Co-op 道具字体乱码

Hello, The Convergence 1.4.2.1 used together with Seamless Co op will cause the font of Seamless Co op props to be garbled

**Comment by Tyfyter** [comment]
@Soinug I would recommend giving this link to someone you know: https://www.adultliteracyleague.org/resources/

**Comment by Soinug** [comment]
Hello,
I'm sorry about the level of English, I'm not fluent and I'm using the translator.
MOD The Convergence1.4.2.1  and MOD Seamless Co-op Merge and use Will make MOD Seamless Co-op  Font chaos

**Comment by Th3M2chine** [comment]
The dlc coming out made it so any time i join through seamless coop its in offline and my character is gone that I spent 200+ hours on.

**Comment by erod7760** [comment]
hello, I am having a problem where whenever  I launch the game it's in offline mode and I can't seem to fix it it keeps timing me out. can someone please help

**Comment by Tyfyter** [comment]
@Soinug, @Th3M2chine, @erod7760, hopefully I have included your language in the google-translate-powered Rosetta stone above, and hopefully it translated successfully

**Comment by Yahirvz** [comment]
The discord links are no longer valid, I want to report some bugs, that my friends and I have been experiencing

**Comment by Tyfyter** [comment]
The discord link is still valid, if you are unable to join it is for a different reason, posting your bugs here will not accomplish anything as all evidence suggests that no one involved in the project looks at the GitHub.

**Comment by Yahirvz** [comment]
image
This is what it shows every time that I click on that link....

**Comment by Tyfyter** [comment]
This is what it shows when I go to that link in a web browser (i.e. not logged into discord)



If you are unable to join with that link it is because _you_ are unable to join, but unfortunately I can't give any information on why that would be

**Comment by Tyfyter** [comment]
Unless you've specifically been clicking the link in the Korean translation, that one might actually be invalid, it looks like Google translate messed that one in particular up

**Comment by keneedy** [comment]
Well, there is nowhere else to report bugs as the developer cut ties with the discord server mentioned here.

So do we have any news if there is going to be another patch? 

And where should we report bugs that are not mentioned in the workarounds?

**Pull request closed without merging**
